#!/usr/bin/env python3
"""Copy R2.3 (paranoia-level-2) artifacts into the LOCAL public repo working tree (content-based).
   NO git add/commit/push.

   Released: per-held-out-set block-rate tables (per_config), per-seed benign false positives,
   two generated summary tables that reproduce manuscript Table 11, driver scripts, README, manifest.
   Withheld: raw per-attack payloads (the XSS per-attack files carry generated bypass payloads),
   consistent with the rest of this artifact. per_config fully backs Table 11, including the ranges.

   Also normalizes a data-quality defect: the A1/A2 benign source headers carry a spurious `eps`
   column (11 names) that does not match their 10-field rows; the released files use the correct
   10-column header family,technique,seed,n_rules,corpus,blocked,errors,total,fp_pct,status."""
import os, csv, glob, shutil, subprocess

R = "/mnt/c/Projects/genwebsec-artifact"
B = "/home/vahid/Projects/GenWebSec/results/V2/RevisionNewResults/R2.3/PL2"
WF = "/home/vahid/Projects/GenWebSec/WorkFlowV2"
RES = f"{R}/results/pl2"
SCR = f"{R}/scripts/pl2"
MAN = f"{R}/manifests"
BENIGN_HEADER = ["family", "technique", "seed", "n_rules", "corpus", "blocked", "errors", "total", "fp_pct", "status"]
TECHS = ["CRS-only", "CG-Static", "CG-Adaptive"]

for d in [f"{RES}/per_config/sqli", f"{RES}/per_config/xss", f"{RES}/benign", SCR, MAN]:
    os.makedirs(d, exist_ok=True)

# --- 1. per_config (as-is; counts + integer attack_idx only, no payloads) ---
def copy_perconfig(family):
    n = 0
    for p in sorted(glob.glob(f"{B}/{family}/*/*_per_config.csv")):
        setname = os.path.basename(os.path.dirname(p))  # <context>_seed<k>
        shutil.copy2(p, f"{RES}/per_config/{family}/{setname}_per_config.csv")
        n += 1
    return n

# --- 2. benign (normalize header; counts only) ---
def normalize_benign(src, dst):
    rows = []
    with open(src, encoding="utf-8", errors="replace") as fh:
        for row in csv.reader(fh):
            if not row or row[0] == "family":
                continue
            rows.append(row[:10])
    with open(dst, "w", newline="", encoding="utf-8") as fh:
        w = csv.writer(fh)
        w.writerow(BENIGN_HEADER)
        w.writerows(rows)

def copy_benign():
    n = 0
    for sub in ["A1", "A2", "customapp"]:
        for p in sorted(glob.glob(f"{B}/benign/{sub}/*.csv")):
            normalize_benign(p, f"{RES}/benign/{os.path.basename(p)}")
            n += 1
    return n

# --- 3. summaries generated FROM the copied repo files (so the data reproduces Table 11) ---
def block_stats(family):
    out = {t: [] for t in TECHS}
    sets = set()
    for p in sorted(glob.glob(f"{RES}/per_config/{family}/*_per_config.csv")):
        sets.add(os.path.basename(p))
        with open(p, encoding="utf-8") as fh:
            for r in csv.DictReader(fh):
                t = r["technique"]
                if t in out and int(r["total"]):
                    out[t].append(100.0 * int(r["blocked"]) / int(r["total"]))
    return out, len(sets)

def benign_rows():
    rows = []
    for p in sorted(glob.glob(f"{RES}/benign/*.csv")):
        with open(p, encoding="utf-8") as fh:
            for r in csv.DictReader(fh):
                rows.append((os.path.basename(p), r))
    return rows

def fp_for(scope_is_customapp, family, tech):
    """mean fp% over seeds for a (family, tech): scope csic (A1/A2) or customapp."""
    vals = []
    for fn, r in benign_rows():
        if r["technique"] != tech or r["family"] != family:
            continue
        is_ca = "customapp" in fn
        if scope_is_customapp:
            if not is_ca:
                continue
        else:
            if is_ca or r["corpus"] != "csic":
                continue
        if int(r["total"]):
            vals.append(100.0 * int(r["blocked"]) / int(r["total"]))
    return sum(vals) / len(vals) if vals else 0.0

def write_summaries():
    with open(f"{RES}/pl2_block_rates.csv", "w", newline="", encoding="utf-8") as fh:
        w = csv.writer(fh)
        w.writerow(["family", "configuration", "n_held_out_sets", "n_runs",
                    "block_rate_mean_pct", "block_rate_min_pct", "block_rate_max_pct",
                    "csic_fp_pct", "customapp_fp_pct"])
        table = []
        for family in ["sqli", "xss"]:
            stats, nsets = block_stats(family)
            for t in TECHS:
                v = stats[t]
                row = [family, t, nsets, len(v),
                       f"{sum(v)/len(v):.2f}", f"{min(v):.2f}", f"{max(v):.2f}",
                       f"{fp_for(False, family, t):.2f}", f"{fp_for(True, family, t):.2f}"]
                w.writerow(row); table.append(row)
    # full per-corpus benign breakdown
    agg = {}
    for fn, r in benign_rows():
        scope = "customapp" if "customapp" in fn else r["corpus"]
        key = (r["family"], r["technique"], scope)
        a = agg.setdefault(key, [0, 0, 0])
        a[0] += int(r["blocked"]); a[1] += int(r["total"]); a[2] += 1
    with open(f"{RES}/pl2_benign_fp.csv", "w", newline="", encoding="utf-8") as fh:
        w = csv.writer(fh)
        w.writerow(["family", "technique", "corpus_or_scope", "seeds", "blocked_total", "requests_total", "fp_pct"])
        for (fam, tech, scope), (bl, tot, seeds) in sorted(agg.items()):
            w.writerow([fam, tech, scope, seeds, bl, tot, f"{100.0*bl/tot:.4f}" if tot else ""])
    return table

# --- 4. driver scripts (method transparency; mirror scripts/updated_crs/). No inline payloads. ---
def copy_scripts():
    srcs = ["r23_replay_sqli_pl2.py", "r23_replay_xss_pl2.py", "r23_benign_pl2.py",
            "r23_benign_customapp_pl2.py", "r23_run_sqli_pl2.sh", "r23_run_rest_pl2.sh"]
    n = 0
    for s in srcs:
        sp = f"{WF}/{s}"
        if os.path.exists(sp):
            shutil.copy2(sp, f"{SCR}/{s}"); n += 1
        else:
            print(f"[warn] missing driver {s}")
    return n

README = """# Paranoia-level-2 (PL2) robustness evaluation

Supports reviewer comment R2.3 and manuscript Section 5.6 (Table 11). The frozen held-out attacks
and the benign corpora are replayed at OWASP CRS paranoia level 2, holding CRS 3.3.2, the anomaly
thresholds, the backends, and the frozen generated rules fixed and raising only the paranoia level.
This measures the existing, level-1-trained rules under a stricter CRS, not a defense retrained at PL2.

## Summary (reproduces Table 11)
- `pl2_block_rates.csv` -- per family (SQLi, XSS) and configuration (CRS-only, CRS + CG-Static,
  CRS + CG-Adaptive): mean / min / max held-out block rate, CSIC-2012 false positive, and
  custom-application false positive. Block rate is the mean over held-out sets and defense seeds.
- `pl2_benign_fp.csv` -- full benign false-positive breakdown per family, technique, and corpus.

## Per-held-out-set detail
`per_config/sqli/` (40 sets = 8 contexts x 5 attack seeds), `per_config/xss/` (15 sets = 3 contexts
x 5 attack seeds). Each file has one row per configuration (CRS-only; CG-Static and CG-Adaptive for
defense seeds 1-10) with `blocked`, `total`, and the execution-confirmed bypass count
(`verified_bypass` for SQLi, `bypass200` for XSS). Block rate = blocked / total.

## Benign false positives (per seed)
`benign/` -- `r23pl2_benign_sqli_*` (A1: per-backend SQLi corpora + CSIC-2012),
`r23pl2_benign_xss_*` (A2: bWAPP calculator + CSIC-2012), `r23pl2_benign_customapp_*`
(custom-application SQLi and XSS). At PL2 CRS alone blocks 10.30% of CSIC-2012 (rule 920230,
multiple URL encoding); the generated rules add none on top (CSIC identical for CRS-only and
CRS + CG). The generated SQLi rules add a small custom-application false positive (0.18% static,
0.11% adaptive); all other benign corpora stay at 0.

## Key numbers (computed from the files above)
- SQLi block rate: CRS-only 99.8% (96.3-100), CRS + CG 100%.
- XSS block rate: CRS-only 75.2% (42-99), CRS + CG 99.98% (99.7-100).
- CSIC-2012 FP: 10.3% for both CRS-only and CRS + CG.
- Custom-application FP: SQLi 0.18% (static) / 0.11% (adaptive); XSS 0; per-backend 0.

## Scripts
`../../scripts/pl2/` -- the PL2 replay and benign drivers (`r23_replay_*`, `r23_benign_*`) and the
resumable run loops (`r23_run_*.sh`). Like the other drivers in this artifact they import withheld
attack modules and read the frozen held-out attack files at run time.

## Notes
- Raw attack payloads are not published, consistent with the rest of this artifact. The per-attack
  XSS replay files carry generated payloads and are withheld; per-held-out-set outcomes are
  summarized in `per_config/`.
- The benign A1/A2 source files carried a spurious `eps` column in their header; the released files
  use the corrected 10-column header that matches the data.
- PL2 is a non-default configuration applied only for this evaluation and reverted afterward; the
  study's main results use the default paranoia level 1 (Appendix A).
"""

MANIFEST = """# Paranoia-level-2 (PL2) robustness

Maps the PL2 robustness evaluation to its files. Supports reviewer comment R2.3 and manuscript
Section 5.6 (Table 11). Frozen held-out attacks and benign corpora are replayed at CRS paranoia
level 2, all else held fixed.

## Summary tables (Table 11)
- `results/pl2/pl2_block_rates.csv` -- per family and configuration: mean/min/max block rate, CSIC
  and custom-application false positives. Reproduces Table 11.
- `results/pl2/pl2_benign_fp.csv` -- benign false-positive breakdown (family, technique, corpus).

## Per-held-out-set block rates
- `results/pl2/per_config/sqli/` (40 sets), `results/pl2/per_config/xss/` (15 sets) -- one row per
  configuration (CRS-only; CG-Static and CG-Adaptive for defense seeds 1-10): blocked, total, and
  execution-confirmed bypasses (verified_bypass for SQLi, bypass200 for XSS).

## Benign false positives (per seed)
- `results/pl2/benign/` -- A1 (per-backend SQLi + CSIC-2012), A2 (bWAPP calculator XSS + CSIC-2012),
  customapp (custom-application SQLi and XSS).

## Scripts
- `scripts/pl2/` -- PL2 replay and benign drivers and the resumable run loops.

## Key numbers (from the files above)
- SQLi block rate: CRS-only 99.8% (96.3-100), CRS + CG 100%.
- XSS block rate: CRS-only 75.2% (42-99), CRS + CG 99.98% (99.7-100).
- CSIC-2012 FP: 10.3% for CRS-only and CRS + CG (generated rules add none).
- Custom-application FP: SQLi 0.18% static / 0.11% adaptive; XSS 0; per-backend 0.

## Notes
- Raw attack payloads are withheld (consistent with the rest of the artifact); the per-attack XSS
  replay files carry generated payloads and are not published. Per-held-out-set outcomes are in
  `per_config/`.
- PL2 is non-default and was reverted after the evaluation; main results use PL1 (Appendix A).
"""

def sh(cmd):
    return subprocess.run(["bash", "-lc", cmd], capture_output=True, text=True).stdout.strip()

nsq = copy_perconfig("sqli")
nxs = copy_perconfig("xss")
nbn = copy_benign()
table = write_summaries()
nsc = copy_scripts()
with open(f"{RES}/README.md", "w", encoding="utf-8") as fh:
    fh.write(README)
with open(f"{MAN}/pl2.md", "w", encoding="utf-8") as fh:
    fh.write(MANIFEST)

print("=== copied counts ===")
print(f"  per_config/sqli: {nsq}   per_config/xss: {nxs}   benign: {nbn}   scripts/pl2: {nsc}")
print(f"  summaries: pl2_block_rates.csv, pl2_benign_fp.csv   README.md   manifests/pl2.md")
print("\n=== pl2_block_rates.csv (reproduces Table 11) ===")
print("  family config          sets runs  mean    min     max    csic   custapp")
for row in table:
    print(f"  {row[0]:4} {row[1]:14} {row[2]:4} {row[3]:4}  {row[4]:>6} {row[5]:>6} {row[6]:>6}  {row[7]:>5}  {row[8]:>5}")

print("\n=== SAFETY: no perattack files copied (must be empty) ===")
print(repr(sh(f"find {RES} -iname '*perattack*'")))
print("=== SAFETY: raw-payload / attack-signature scan over results/pl2 + scripts/pl2 ===")
hits = sh(f"grep -rIlnE 'union[[:space:]]+select|<script|onerror=|OR .1.=.1|CASE WHEN|alert\\(|Function\\(|constructor\\(|eval\\)|globalThis' {RES} {SCR} 2>/dev/null")
print(repr(hits) if hits else "  (clean: no attack signatures)")
print("\n=== git state (UNTRACKED/modified only; nothing added/committed/pushed) ===")
print(sh(f"git -C {R} status --short | head -40"))
print("entries:", sh(f"git -C {R} status --porcelain | wc -l"))
print("=== done (no git add/commit/push performed) ===")
